# Generated by Django 5.0.8 on 2025-10-02 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("musics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listening_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musics.playlist"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="musics.album",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="musics.artist",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musics.track"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                related_name="in_playlists",
                through="musics.PlaylistTrack",
                to="musics.track",
            ),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listened_by",
                to="musics.track",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="musics.track",
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["release_date"], name="musics_albu_release_4c16a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist"], name="musics_albu_artist__b371f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["genre"], name="musics_trac_genre_bf0e09_idx"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["-plays_count", "is_published"],
                name="musics_trac_plays_c_72f44d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["-likes_count", "is_published"],
                name="musics_trac_likes_c_2cbf8f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("name", "artist"), name="unique_track_per_artist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlisttrack",
            unique_together={("playlist", "track")},
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["owner", "is_public"], name="musics_play_owner_i_e1fc34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["user", "listened_at"], name="musics_list_user_id_a8fecb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["track", "listened_at"], name="musics_list_track_i_e5e696_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["track", "created_at"], name="musics_like_track_i_47da46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "created_at"], name="musics_like_user_id_f39825_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "track")},
        ),
    ]
