# Generated by Django 5.0.8 on 2025-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0003_album_owner_artist_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "db_table": "musics_genres",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="track",
            name="musics_trac_genre_bf0e09_idx",
        ),
        migrations.AddField(
            model_name="track",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="track",
            name="release_date",
            field=models.DateField(blank=True, null=True, verbose_name="Release Date"),
        ),
        migrations.RemoveField(
            model_name="track",
            name="genre",
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(fields=["name"], name="musics_genr_name_67a5d0_idx"),
        ),
        migrations.AddField(
            model_name="track",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="tracks", to="musics.genre"
            ),
        ),
    ]
