# Generated by Django 5.0.8 on 2025-11-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0004_genre_remove_track_musics_trac_genre_bf0e09_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="genre",
            new_name="genres",
        ),
    ]
