# Generated by Django 5.0.8 on 2025-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0005_rename_genre_track_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                blank=True, default=1, max_length=120, unique=True, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
    ]
