# Generated by Django 5.0.8 on 2025-11-08 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0006_remove_genre_created_at_remove_genre_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listeninghistory",
            name="additional_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata about the listening session",
            ),
        ),
        migrations.AlterField(
            model_name="listeninghistory",
            name="listened_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="listeninghistory",
            unique_together={("user", "track")},
        ),
    ]
