# Generated by Django 5.0.8 on 2025-11-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0007_listeninghistory_additional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genre",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Genre"
            ),
        ),
    ]
