# Generated by Django 5.0.8 on 2025-11-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0008_album_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="album",
        ),
        migrations.AddField(
            model_name="track",
            name="albums",
            field=models.ManyToManyField(
                blank=True, related_name="tracks", to="musics.album"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="musics.genre",
                verbose_name="Genre",
            ),
            preserve_default=False,
        ),
    ]
