# Generated by Django 5.0.8 on 2025-11-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0009_remove_track_album_track_albums_alter_album_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="albums",
        ),
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="musics.album",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Genre"
            ),
        ),
    ]
