# Generated by Django 5.0.8 on 2025-11-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0010_remove_track_albums_track_album_alter_album_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="genre",
        ),
    ]
