# Generated by Django 5.0.8 on 2025-11-12 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0011_remove_album_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
            },
        ),
        migrations.AlterModelOptions(
            name="playlisttrack",
            options={
                "ordering": ["order"],
                "verbose_name": "Playlist Track",
                "verbose_name_plural": "Playlist Tracks",
            },
        ),
        migrations.AlterModelOptions(
            name="track",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="album",
            name="likes_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="listens_last_month",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="listens_last_week",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="plays_count",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="artist",
            name="followers_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="artist",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified artist"),
        ),
        migrations.AddField(
            model_name="artist",
            name="total_likes",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="artist",
            name="total_plays",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="playlist",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="playlists/covers/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_playlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Followers",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="total_duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Calculated automatically based on tracks duration.",
                verbose_name="Total Duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="added_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="bitrate",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Bitrate (kbps)"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="bpm",
            field=models.PositiveIntegerField(
                blank=True, help_text="Beats per minute", null=True
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="download_count",
            field=models.BigIntegerField(default=0, verbose_name="Download Count"),
        ),
        migrations.AddField(
            model_name="track",
            name="featured_artists",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_tracks",
                to="musics.artist",
                verbose_name="Featured Artists",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="is_explicit",
            field=models.BooleanField(default=False, verbose_name="Explicit Content"),
        ),
        migrations.AddField(
            model_name="track",
            name="language",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Language"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="lyrics",
            field=models.TextField(blank=True, null=True, verbose_name="Lyrics"),
        ),
        migrations.AddField(
            model_name="track",
            name="mood",
            field=models.CharField(
                blank=True,
                help_text="e.g. Chill, Energetic, Sad, Romantic",
                max_length=100,
                null=True,
                verbose_name="Mood / Vibe",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="youtube_url",
            field=models.URLField(blank=True, null=True, verbose_name="YouTube URL"),
        ),
        migrations.AlterField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is published"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional data such as social links, country, etc.",
                verbose_name="Meta data",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(
                related_name="in_playlists",
                through="musics.PlaylistTrack",
                to="musics.track",
                verbose_name="Tracks",
            ),
        ),
        migrations.AlterField(
            model_name="playlisttrack",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_tracks",
                to="musics.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="musics.album",
                verbose_name="Album",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="musics.artist",
                verbose_name="Artist",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="audio",
            field=models.FileField(
                upload_to="tracks/audio/", verbose_name="Audio File"
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tracks/covers/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="tracks",
                to="musics.genre",
                verbose_name="Genres",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["-plays_count"], name="musics_albu_plays_c_fd517e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["-likes_count"], name="musics_albu_likes_c_37f6f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["-followers_count"], name="musics_arti_followe_d6a781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["-total_plays"], name="musics_arti_total_p_6c7dbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["slug"], name="musics_play_slug_52b584_idx"),
        ),
    ]
