# Generated by Django 5.0.8 on 2025-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0012_alter_playlist_options_alter_playlisttrack_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="album",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
