# Generated by Django 5.0.8 on 2025-10-03 08:07

import apps.users.models.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="expires_at",
            field=models.DateTimeField(default=apps.users.models.tokens.default_expiry),
        ),
    ]
