# Generated by Django 5.0.8 on 2025-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usertoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/images/default-avatar.jpg",
                null=True,
                upload_to="avatars/%Y/%M/%d",
            ),
        ),
    ]
