# Generated by Django 5.0.8 on 2025-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/default/default-avatar.jpg",
                null=True,
                upload_to="avatars/%Y/%M/%d",
            ),
        ),
    ]
