#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Apply Django migrations
#python manage.py makemigrations
python manage.py migrate

# Collect static files
python manage.py collectstatic --noinput

# Run Gunicorn server using WSGI
# exec gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 120

# Run Uvicorn server using ASGI
# exec uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload

# Run Gunicorn with Uvicorn workers
gunicorn core.asgi:application \
    -k uvicorn.workers.UvicornWorker \
    --bind 0.0.0.0:8000 \
    --workers 4 \
    --timeout 120 \
    --log-level info
